"""add user_id to tasks

Revision ID: 26c2572077c7
Revises: 37d3dde0b8d1
Create Date: 2026-10-07 09:54:10.350983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c2572077c7'
down_revision: Union[str, Sequence[str], None] = '37d3dde0b8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    # 把「還沒有主人」的舊任務，指給 users 表裡最小的 id（你的是 testuser）
    op.execute("UPDATE tasks SET user_id = (SELECT min(id) FROM users) WHERE user_id IS NULL")
    op.create_foreign_key('fk_tasks_user_id_users', 'tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_user_id_users', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###
